name: inventory_app
description: a good app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  flutter_slidable: ^3.1.0
  cupertino_icons: ^1.0.6
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.1
  path_provider: ^2.1.4
  image_gallery_saver: ^2.0.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
